### ISSUE TITLE
Issue building on windows container

### ISSUE THREAD

**Issue by thisismalhotra** [asmagin/jenkins-on-windowsservercore#4]
I get this error while building master. No matter which folder I change to the same error happens. Any tips? I am fairly new to docker

`
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 147894ee4dd9155100837e24b208c93e33a00a89372c3666344a586ab578a67b encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"-v C:\\Users\\Public\\JenkinsData:C:\\Jenkins","WorkingDirectory":"C:\\","Environment":{"JAVA_HOME":"C:\\ojdkbuild","JAVA_OJDKBUILD_SHA256":"99a842b88b42c049ba4ffc3b13a9b98fbdad818703750e319ae59aa717e95ad3","JAVA_OJDKBUILD_VERSION":"1.8.0.121-2","JAVA_OJDKBUILD_ZIP":"java-1.8.0-openjdk-1.8.0.121-2.b13.ojdkbuild.windows.x86_64.zip","JAVA_VERSION":"8u121"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[42,125]}.
`

**Comment by asmagin** [comment]
You might have issues with mapping, maybe host folders are not there or you trying to map to something that is a file instead of a directory.
Try to check out this thread: https://github.com/docker/for-win/issues/212

**Comment by thisismalhotra** [comment]
same issue even with this command 

`docker run -it --rm asmagin/jenkins-on-windowsservercore -v "$(pwd):c:\jenkins"`

**Comment by thisismalhotra** [comment]
Woo-hoo, thanks for the help.

Finally got it to work with this command

docker run -it --rm -v "$(pwd):c:\jenkins" asmagin/jenkins-on-windowsservercore 

Not sure why moving the -v part in front made it work

Not sure how to contact you but I would also like to know how can I update jenkins version and msbuild version in this

**Comment by asmagin** [comment]
It is tricky with Jenkins version, they trying to make it more secure out of the box and actually screwed up automated installation (at least it was like that a year ago.)

For msbuild: either update slave dockerfile and generate your own image or reference this one and put new MSBuild on top.
